# Funding platforms
# This file allows you to sponsor the project maintainers
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (uncomment and add your username if you have GitHub Sponsors enabled)
# github: aliraxa29

# Patreon (uncomment and add your username if you have a Patreon)
# patreon: username

# Ko-fi
ko_fi: aliraxa

# Buy Me a Coffee (uncomment and add your username)
# buy_me_a_coffee: username
